# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY voice_avatar_react/package.json voice_avatar_react/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend application code
COPY ./voice_avatar_react /app

# Expose the port the app runs on
EXPOSE 8600

# Command to run the application
CMD ["npm", "run", "dev", "--", "--host"]
